id: verilogeval_spec_to_rtl_prob010_mt2015_q4a
source: verilogeval
license: verilog-eval
language: systemverilog
family: misc_hdl
tags:
- combinational
- verilog
difficulty: 2
prompt: "I would like you to implement a module named TopModule with the following\n\
  interface. All input and output ports are one bit unless otherwise\nspecified.\n\
  \n - input  x\n - input  y\n - output z\n\nThe module should implement the boolean\
  \ function z = (x^y) & x."
top_module: TopModule
ports: []
expected:
  type: reference_module
  file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob010_mt2015_q4a_ref.sv
evaluation:
  lint: true
  simulation: true
  formal: false
  testbench_file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob010_mt2015_q4a_test.sv
  pass_regex: Mismatches:\s+0\s+in\s+\d+\s+samples
split:
  default: holdout
