id: verilogeval_spec_to_rtl_prob048_m2014_q4c
source: verilogeval
license: verilog-eval
language: systemverilog
family: misc_hdl
tags:
- sequential
- verilog
difficulty: 2
prompt: "I would like you to implement a module named TopModule with the following\n\
  interface. All input and output ports are one bit unless otherwise\nspecified.\n\
  \n - input  clk\n - input  d\n - input  r\n - output q\n\nThe module should implement\
  \ a simple D flip flop with active high\nsynchronous reset (reset output to 0)."
top_module: TopModule
ports: []
expected:
  type: reference_module
  file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob048_m2014_q4c_ref.sv
evaluation:
  lint: true
  simulation: true
  formal: false
  testbench_file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob048_m2014_q4c_test.sv
  pass_regex: Mismatches:\s+0\s+in\s+\d+\s+samples
split:
  default: validation
