id: verilogeval_spec_to_rtl_prob045_edgedetect2
source: verilogeval
license: verilog-eval
language: systemverilog
family: misc_hdl
tags:
- sequential
- verilog
difficulty: 2
prompt: "I would like you to implement a module named TopModule with the following\n\
  interface. All input and output ports are one bit unless otherwise\nspecified.\n\
  \n - input clk\n - input in       (8 bits)\n - output anyedge (8 bits)\n\nImplement\
  \ a module that for each bit in an 8-bit input vector, detect\nwhen the input signal\
  \ changes from one clock cycle to the next (detect\nany edge). The output bit of\
  \ anyedge should be set to 1 the cycle \nafter the input bit has 0 to 1 or 1 to\
  \ 0 transition occurs. Assume all \nsequential logic is triggered on the positive\
  \ edge of the clock."
top_module: TopModule
ports: []
expected:
  type: reference_module
  file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob045_edgedetect2_ref.sv
evaluation:
  lint: true
  simulation: true
  formal: false
  testbench_file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob045_edgedetect2_test.sv
  pass_regex: Mismatches:\s+0\s+in\s+\d+\s+samples
split:
  default: evolution
