id: verilogeval_spec_to_rtl_prob056_ece241_2013_q7
source: verilogeval
license: verilog-eval
language: systemverilog
family: misc_hdl
tags:
- sequential
- verilog
difficulty: 2
prompt: "I would like you to implement a module named TopModule with the following\n\
  interface. All input and output ports are one bit unless otherwise\nspecified.\n\
  \n - input  clk\n - input  j\n - input  k\n - output Q\n\nThe module should implement\
  \ a JK flip-flop with the following truth\ntable. Note: Qold is the output of the\
  \ flip-flop before the positive\nclock edge.\n\n  J | K | Q\n  0 | 0 | Qold\n  0\
  \ | 1 | 0\n  1 | 0 | 1\n  1 | 1 | ~Qold"
top_module: TopModule
ports: []
expected:
  type: reference_module
  file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob056_ece241_2013_q7_ref.sv
evaluation:
  lint: true
  simulation: true
  formal: false
  testbench_file: benchmarks/external/raw/verilogeval/c498220d0a52248f8e3fdffe279075215bde2da6/dataset_spec-to-rtl/Prob056_ece241_2013_q7_test.sv
  pass_regex: Mismatches:\s+0\s+in\s+\d+\s+samples
split:
  default: evolution
